"use client";
import { useMemo, useState } from "react";
import { Building2, CheckCheck, ChevronDown, CircleHelp, Mail, Menu, MessageSquareText, MoreHorizontal, Paperclip, Plus, Search, Send, Settings, Star, Tag, Users, X } from "lucide-react";
type Conversation={id:number;name:string;email:string;company:string;initials:string;color:string;preview:string;time:string;unread:number;status:string};
const initialConversations:Conversation[]=[
{id:1,name:"محمد الصوفي",email:"m.alsufi@example.com",company:"متجر رواسي",initials:"م ص",color:"#5c6ac4",preview:"وصلت الحوالة، هل يمكن تنفيذ الطلب اليوم؟",time:"10:42",unread:2,status:"طلب مفتوح"},
{id:2,name:"سارة القحطاني",email:"sarah@noor.sa",company:"نور للتجارة",initials:"س ق",color:"#9d6f42",preview:"شكرًا، تم استلام الفاتورة بنجاح.",time:"أمس",unread:0,status:"تم الحل"},
{id:3,name:"أحمد الحكيمي",email:"ahmed@almadar.co",company:"المدار",initials:"أ ح",color:"#267c6e",preview:"نحتاج عرض سعر لخمسين بطاقة.",time:"أمس",unread:1,status:"بانتظار الرد"},
{id:4,name:"ريم عبدالله",email:"reem@example.com",company:"عميلة فردية",initials:"ر ع",color:"#965b72",preview:"هل يمكن تعديل اسم المستفيد؟",time:"السبت",unread:0,status:"طلب مفتوح"},
{id:5,name:"شركة السهم",email:"finance@alsahm.com",company:"شركة السهم",initials:"س",color:"#476886",preview:"مرفق كشف العمليات لهذا الأسبوع.",time:"الخميس",unread:0,status:"متابعة"}];
const seededMessages=[{id:1,mine:false,text:"السلام عليكم، قمنا بتحويل المبلغ المطلوب صباح اليوم.",time:"10:31"},{id:2,mine:false,text:"وصلت الحوالة، هل يمكن تنفيذ الطلب اليوم؟",time:"10:32"},{id:3,mine:true,text:"وعليكم السلام يا محمد، وصلت رسالتك. سأراجع الحوالة مع الحسابات وأؤكد لك خلال دقائق.",time:"10:36"},{id:4,mine:false,text:"ممتاز، شكرًا لك. ننتظر تأكيدكم.",time:"10:42"}];
export default function Home(){
const[conversations,setConversations]=useState(initialConversations),[selected,setSelected]=useState(1),[query,setQuery]=useState(""),[filter,setFilter]=useState("الكل"),[draft,setDraft]=useState(""),[messages,setMessages]=useState(seededMessages),[showNew,setShowNew]=useState(false),[mobileList,setMobileList]=useState(true);
const active=conversations.find(c=>c.id===selected)??conversations[0];
const filtered=useMemo(()=>conversations.filter(c=>`${c.name} ${c.email} ${c.company}`.toLowerCase().includes(query.toLowerCase())&&(filter==="الكل"||(filter==="غير مقروء"&&c.unread>0)||(filter==="مفتوحة"&&c.status!=="تم الحل"))),[conversations,query,filter]);
function openConversation(id:number){setSelected(id);setMobileList(false);setConversations(items=>items.map(c=>c.id===id?{...c,unread:0}:c))}function sendMessage(){if(!draft.trim())return;setMessages(items=>[...items,{id:Date.now(),mine:true,text:draft.trim(),time:"الآن"}]);setDraft("")}
return <main dir="rtl" className="app-shell">
<aside className="rail"><div className="logo-mark">خ</div><nav aria-label="التنقل الرئيسي"><button className="rail-item active" title="المحادثات"><MessageSquareText/></button><button className="rail-item" title="العملاء"><Users/></button><button className="rail-item" title="الوسوم"><Tag/></button><button className="rail-item" title="التقارير"><Building2/></button></nav><div className="rail-bottom"><button className="rail-item"><CircleHelp/></button><button className="rail-item"><Settings/></button><div className="profile-dot">هـ</div></div></aside>
<section className={`inbox-panel ${mobileList?"mobile-show":"mobile-hide"}`}><header className="inbox-head"><div><p className="eyebrow">مساحة عمل أمد</p><h1>المحادثات</h1></div><button className="primary-icon" onClick={()=>setShowNew(true)} aria-label="محادثة جديدة"><Plus/></button></header><div className="search-wrap"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث باسم العميل أو بريده"/></div><div className="filters">{["الكل","غير مقروء","مفتوحة"].map(item=><button key={item} onClick={()=>setFilter(item)} className={filter===item?"selected":""}>{item}</button>)}</div><div className="conversation-list">{filtered.map(c=><button key={c.id} onClick={()=>openConversation(c.id)} className={`conversation-card ${selected===c.id?"selected":""}`}><span className="avatar" style={{background:c.color}}>{c.initials}</span><span className="conversation-copy"><span className="row"><strong>{c.name}</strong><small>{c.time}</small></span><span className="company">{c.company}</span><span className="row"><span className="preview">{c.preview}</span>{c.unread>0&&<b className="unread">{c.unread}</b>}</span></span></button>)}{filtered.length===0&&<div className="empty-state">لا توجد محادثات مطابقة</div>}</div></section>
<section className={`chat-panel ${!mobileList?"mobile-show":"mobile-hide"}`}><header className="chat-head"><button className="mobile-back" onClick={()=>setMobileList(true)}><Menu/></button><span className="avatar" style={{background:active.color}}>{active.initials}</span><div className="chat-person"><strong>{active.name}</strong><span>{active.email}</span></div><span className="status-pill"><span/>{active.status}</span><button className="icon-button"><Star/></button><button className="icon-button"><MoreHorizontal/></button></header><div className="thread"><div className="date-divider"><span>اليوم</span></div>{messages.map(m=><div key={m.id} className={`message-row ${m.mine?"mine":"theirs"}`}><div className="bubble"><p>{m.text}</p><span>{m.time}{m.mine&&<CheckCheck/>}</span></div></div>)}</div><footer className="composer"><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage()}}} placeholder={`اكتب ردًا إلى ${active.name}…`}/><div className="composer-actions"><div><button><Paperclip/></button><button><MoreHorizontal/></button></div><button className="send-button" onClick={sendMessage}><Send/>إرسال</button></div><span className="email-note"><Mail/> سيصل الرد إلى {active.email} عبر البريد الإلكتروني</span></footer></section>
<aside className="details-panel"><div className="details-top"><span>بيانات العميل</span><button><X/></button></div><div className="customer-card"><span className="large-avatar" style={{background:active.color}}>{active.initials}</span><h2>{active.name}</h2><p>{active.company}</p></div><dl><div><dt>البريد الإلكتروني</dt><dd>{active.email}</dd></div><div><dt>رقم العميل</dt><dd>KH-{String(active.id).padStart(4,"0")}</dd></div><div><dt>الموظف المسؤول</dt><dd><span className="mini-avatar">هـ</span> هشام</dd></div><div><dt>حالة المحادثة</dt><dd><button className="select-like">{active.status}<ChevronDown/></button></dd></div></dl><div className="labels"><h3>الوسوم <button><Plus/></button></h3><div><span>عميل مهم</span><span>مبيعات</span></div></div><button className="resolve-button"><CheckCheck/>إغلاق المحادثة</button></aside>
{showNew&&<div className="modal-backdrop" onMouseDown={()=>setShowNew(false)}><form className="new-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();setShowNew(false)}}><div className="modal-title"><div><p className="eyebrow">محادثة جديدة</p><h2>إضافة عميل بالبريد</h2></div><button type="button" onClick={()=>setShowNew(false)}><X/></button></div><label>اسم العميل<input required placeholder="مثال: عبدالله محمد"/></label><label>البريد الإلكتروني<input required type="email" placeholder="customer@example.com"/></label><label>اسم الشركة<input placeholder="اختياري"/></label><label>موضوع الرسالة<input required placeholder="كيف يمكننا مساعدتك؟"/></label><div className="modal-actions"><button type="button" onClick={()=>setShowNew(false)}>إلغاء</button><button className="primary-action" type="submit">بدء المحادثة</button></div></form></div>}
</main>}
